/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */
package src.main.scalate.app

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._

object $_scalate_$AppAction_jade {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    import _root_.org.fusesource.scalate.support.RenderHelper.{sanitize=>$_scalate_$_sanitize, preserve=>$_scalate_$_preserve, indent=>$_scalate_$_indent, smart_sanitize=>$_scalate_$_smart_sanitize, attributes=>$_scalate_$_attributes}
    ;{
      val helper: xitrum.Action = $_scalate_$_context.attribute("helper")
      import helper._
      ;{
        val context: org.fusesource.scalate.RenderContext = $_scalate_$_context.attribute("context")
        import context._
        
        
        $_scalate_$_context << ( "<body>\n  <p>This is an action in main module (\"app\" module1).</p>\n  <p>\n    <a" );
        $_scalate_$_context << $_scalate_$_attributes( $_scalate_$_context, List( (
            "href"
          ,
                        url[module1.dbc]

        ) ) )
        $_scalate_$_context << ( ">Link to action in database</a>\n  </p>\n</body>\n" );
      }
    }
  }
}


class $_scalate_$AppAction_jade extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$AppAction_jade.$_scalate_$render(context)
}
